encyclopedia/urls.py
from django.urls import path

from . import views
import re
app_name = 'encyclopedia'
urlpatterns = [

    path("wiki", views.index, name="index"),
    path("wiki/<str:name_title>",views.ml,name="gi"),
    path("search",views.lame,name="lame"),
    path("add",views.add,name="add"),
    path("rando/", views.random_name, name="random_name"),
    path("edit/<str:selectedit>", views.modify, name="modify"),
    #path("take",views.take,name="take")
]

wiki/urls.py
from django.contrib import admin
import re
from django.urls import include, path

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
    #url(r'^encyclopedia/', include('encyclopedia.urls'), namespace="encyclopedia"),
    #url(r'^/encyclopedia/', include('encyclopedia.urls', namespace='encyclopedia', app_name='encyclopedia'))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/forms.py
from django import forms
from . import views
from . import util
from django.shortcuts import render
from django.urls import resolve
from django.http import HttpResponseRedirect, Http404
from django import forms
import markdownify, os
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from django.views.generic.base import TemplateView
from . import util
from django.shortcuts import redirect
import random


class AddForm(forms.Form):


    tile= forms.CharField(label="Title")
    Added= forms.CharField(widget=forms.Textarea,label="")

class Editls(forms.Form):
    formtitle= forms.CharField(label="Title")
    Editform= forms.CharField(widget=forms.Textarea,label="")

encyclopedia/views.py
from django.shortcuts import render
from django.urls import resolve , reverse
from django.http import HttpResponseRedirect, Http404
from django import forms
import markdownify, os
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from django.views.generic.base import TemplateView
from . import util
from django.shortcuts import redirect
import random
from . import forms
from .forms import AddForm
from .forms import Editls



def random_name(request):
    entries = util.list_entries() # list of wikis
    selected_page = random.choice(entries)

    return redirect('encyclopedia:gi', name_title=selected_page)


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

###URL path find
def ml(request,name_title):
    return render(request, "ent/sm.html", {
        "entries": util.get_entry(name_title)

    })
#####Search
def lame(request):
    sa = request.POST['abz']
    if sa=='' or not util.get_entry(sa):
      return render(request,"notfound/nfound.html")
    return redirect('encyclopedia:gi', name_title=sa)

####save entryml
def add(request):
    if request.method=='POST' or 'GET':
        form =AddForm(request.POST)

        if form.is_valid():

            tile=form.cleaned_data["tile"]
            Added=form.cleaned_data["Added"]

            #return HttpResponseRedirect('/wiki')
        else:
           return  render(request,"add/add.html",{
             "form": AddForm(),
           })

    #tile=form.cleaned_data["tile"]
    #Added=form.cleaned_data["Added"]

    return  render(request,"add/add.html",{
      "form": form,
      "entries":util.save_entry(tile,Added)

    })

### edit page
def modify(request,selectedit):

    content = util.get_entry(selectedit)
    #content = util.get_entry(editPage)
    man={"formtitle":selectedit,"Editform":content}
    form =Editls(request.POST,man)
    data=request.POST.copy()
    if request.method =="POST" or None:

       data=request.POST.copy()
       formtitle= data.get('formtitle')
       Editform= data.get('Edit')

    formtitle="LISTS"
    Editform= "LIST"
    return render(request, "ent/edit.html",{
    "entries":util.save_entry(formtitle,Editform),
    "form":form,
    "page_title":selectedit
    })

encyclopedia/templates/add/add.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1 style="color:purple">Create New Page</h1>
    <form  action="{% url 'encyclopedia:add' %}" method="post">
       {%csrf_token%}
        {{form}}
       <input type="submit" value="submit" />
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
          <a href="wiki/{{entry}}" style="color:red" /> <li>{{ entry }}</li>

        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2 style="color:purple">Wiki</h2>
                <form  action="{% url 'encyclopedia:lame' %}" method="post">
                   {%csrf_token%}
                    <input name="abz" class="search" type="text" placeholder="Search Encyclopedia" id="abz">
                    <input type="submit" value="submit">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="/add">Create New Page</a>
                </div>
                <div>
                  <a href="{% url 'encyclopedia:random_name' %}">Random Page</a>
                </div>



                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/ent/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}

{% endblock %}

{% block body %}
    <h1>{{page_title}}</h1>
    <form action="{% url 'encyclopedia:modify' page_title %}" method="POST">
        {% csrf_token %}
           {{form}}
        <input type="submit" value="submit">

    </form>
{% endblock %}

encyclopedia/templates/ent/gandu.html
{% extends "encyclopedia/layout.html" %}



{% block body %}

{% load markdownify%}
{{ entries|markdownify}}



<div>
    <a href="">editpage</a>
</div>
{% endblock %}

encyclopedia/templates/ent/sm.html
{% extends "encyclopedia/layout.html" %}



{% block body %}
{% load markdownify%}
{{ entries|markdownify}}
{% endblock %}

encyclopedia/templates/notfound/nfound.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1 style="text-align:center;color:red">Page Not Found</h1>
    <h2 style="text-align:center;color:blue">Please Try Relavent Page</h2>


{% endblock %}